config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'notes#index'

  get '/about', to: 'static_pages#about'

  resources :notes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
    render partial: 'form'
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def new
    @note = Note.new
    render partial: 'form'
  end

  def create
    @note = Note.new(note_params)
      
     if @note.save
       redirect_to notes_path
     else
       render :new
     end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
  def note_params
    params.require(:note).permit(:title, :author, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MyNotes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link"><%= link_to 'Home', root_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to 'About', about_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to 'Notes', notes_path %></a>
      </li>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link"><%= link_to 'Create a Note', new_note_path %></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<h1><%= @note.id ? 'Edit Note' : 'Create Note' %></h1>
<%= form_for @note do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field(:title, {:class => 'form-control'}) %> <br>

  <%= f.label :author %><br>
  <%= f.text_field :author, required: true, placeholder: 'Author' %><br>

  <%= f.label :body %><br>
  <%= f.text_area :body, required: true %><br>

  <button type="button" class="btn btn-light"><%= f.submit %></button>
<% end %>

<button type="button" class="btn btn-light"><%= link_to 'Back', notes_path %></button>

app/views/notes/index.html.erb
<h1>Notes</h1>


<ul class = 'note'>
<% @notes.each do |note|%>
  <li><%= link_to note.title, note_path(note)%></li>
<% end %>
</ul>

<button type="button" class="btn btn-light"><%= link_to 'Create New Note', new_note_path %></button>

app/views/notes/show.html.erb
<h1><%=  @note.title %></h1>
<h3><%=  @note.author %></h3>
<p><%=  @note.body %></p>

<br>

<button type="button" class="btn btn-light"><%= link_to 'Edit note', edit_note_path(@note) %></button>
<button  type="button" class="btn btn-light"><%= link_to "Delete Note", @note, method: :delete %></button>

<br>

<button type="button" class="btn btn-light"><%= link_to 'Go Back', notes_path%></button>